import {
  XIcon,
  ReactIcon,
  NextjsIcon,
  TailwindIcon,
  MongoDbIcon,
  PostgresIcon,
  SqlIcon,
  HtmlIcon,
  CssIcon,
  JsIcon,
  TsIcon,
  NpmIcon,
  ReduxIcon,
  GraphQlIcon,
  ExpressIcon,
  DevIcon,
  SassIcon,
  WebPackIcon,
  DockerIcon,
  GitIcon,
  GoogleIcon,
  GitHubIcon,
} from "./icons";

export const normalIcons = [
  { name: "reacticon", icon: <ReactIcon />, iconName: "ReactIcon" },
  { name: "nextjsicon", icon: <NextjsIcon />, iconName: "NextjsIcon" },
  { name: "tailwindicon", icon: <TailwindIcon />, iconName: "TailwindIcon" },
  { name: "mongodbicon", icon: <MongoDbIcon />, iconName: "MongoDbIcon" },
  { name: "postgresicon", icon: <PostgresIcon />, iconName: "PostgresIcon" },
  { name: "sqlicon", icon: <SqlIcon />, iconName: "SqlIcon" },
  { name: "htmlicon", icon: <HtmlIcon />, iconName: "HtmlIcon" },
  { name: "cssicon", icon: <CssIcon />, iconName: "CssIcon" },
  { name: "jsicon", icon: <JsIcon />, iconName: "JsIcon" },
  { name: "tsicon", icon: <TsIcon />, iconName: "TsIcon" },
  { name: "npmicon", icon: <NpmIcon />, iconName: "NpmIcon" },
  { name: "reduxicon", icon: <ReduxIcon />, iconName: "ReduxIcon" },
  { name: "graphqlicon", icon: <GraphQlIcon />, iconName: "GraphQlIcon" },
  { name: "expressicon", icon: <ExpressIcon />, iconName: "ExpressIcon" },
  { name: "devicon", icon: <DevIcon />, iconName: "DevIcon" },
  { name: "webpackicon", icon: <WebPackIcon />, iconName: "WebPackIcon" },
  { name: "sassicon", icon: <SassIcon />, iconName: "SassIcon" },
  { name: "dockericon", icon: <DockerIcon />, iconName: "DockerIcon" },
  { name: "xicon", icon: <XIcon />, iconName: "XIcon" },
  { name: "giticon", icon: <GitIcon />, iconName: "GitIcon" },
  { name: "googleicon", icon: <GoogleIcon />, iconName: "GoogleIcon" },
  { name: "githubicon", icon: <GitHubIcon />, iconName: "GitHubIcon" },
];
